# -*- coding: utf-8 -*-
"""popularitywithchatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N3vjoyz48pKF8s55zcvwT0VVP7fUVCXz
"""

# Option 1
genres = ['Comedy', 'Drama', 'Thriller']

st.title("Personal Recommender")
st.write("Hi! I'm your personal recommender.")

genre = st.radio("Choose your genre:", genres)

if genre:
    st.write(f"You have chosen {genre}")
    df = popularity_based_recommender(15)
    if genre == 'Comedy':
        a = df[df["genres"].str.contains("Comedy")]
    elif genre == 'Drama':
        a = df[df["genres"].str.contains("Drama")]
    elif genre == 'Thriller':
        a = df[df["genres"].str.contains("Thriller")]
    else:
        st.write("Invalid genre selection")

    if not a.empty:
        st.write("Recommended movies:")
        st.table(a[['title']].reset_index(drop=True))
    else:
        st.write("No recommendations found for this genre.")

# FOR CHAT BOT !!!

import streamlit as st
import pandas as pd
from your_popularity_based_recommender_module import popularity_based_recommender


csv_url = "https://raw.githubusercontent.com/Veronica-MN/wbsflix_streamlit_app/main/sample_movies.csv"

def popularity_recommender(num_recommendations):
  try:
      movie_data = pd.read_csv(csv_url)
      movie_data['rating'] = calculate_popularity(movie_data)
      sorted_movies = movie_data.sort_values(by='rating', ascending=False)
      recommended_movies = sorted_movies.head(num_recommendations)
      return recommended_movies
  except Exception as e:
        print(f"Error: {e}")
        return None

def calculate_popularity(movie_data):
  average_ratings = movie_data.groupby('movieId')['rating'].mean()
  popularity_score = (average_ratings * np.log1p(movie_data['rating'].count())).fillna(0)

    
 return popularity_score


genres = {'1': 'Comedy', '2': 'Drama', '3': 'Thriller'}

st.title("Personal Recommender")
st.chat_message("assistant", "Hi! I'm your personal recommender Human!!!")

while True:
    st.chat_message("assistant", "Please choose a movie genre:")
    genre_choice = st.text_input("Choose, 1 = Comedy, 2 = Drama, 3 = Thriller")

    if genre_choice not in genres:
        st.chat_message("assistant", "Invalid genre selection. Please choose 1, 2, or 3.")
    else:
        selected_genre = genres[genre_choice]
        st.chat_message("user", f"You have chosen {selected_genre}")


        recommended_movies = popularity_recommender(10)


        a = recommended_movies[recommended_movies["genres"].str.contains(selected_genre)]

        if not a.empty:
            st.chat_message("assistant", "Here are your personal movie recommendations, Enjoy!:")
            for movie_title in a['title']:
                st.chat_message("assistant", movie_title)
        else:
            st.chat_message("assistant", "No recommendations found now, sorry.")

    continue_chat = st.radio("Do you want another recommendation?", ["Yes", "No"])
    if continue_chat == "No":
        break